### ISSUE TITLE
dumb as hell code

### ISSUE THREAD

**Issue by Kowng** [Daeon97/sketch_feb17a#1]
please do better please

**Comment by Kowng** [comment]
and please don't reply your code is just shiat

**Comment by Daeon97** [comment]
Idiot 😂

**Comment by Kowng** [comment]
> Idiot 😂

but its your code that is the problem so pointless wasting github server resources keeping this saved

**Comment by Daeon97** [comment]
Closing this issue for now. I believe i have solved this issue 😂
